server:
  port: 1001

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092

spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

spring.redis:
  host: localhost
  port: 6379
